version: '3'
services:
  react:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
   
      

  node:
    container_name: backend
    build:
      context: .
    ports:
      - "8888:8888"
    env_file:
      - .variables.env
    
    
    
      

