name: Deploy

on:
  push:
    branches:
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: 'lalami.sdn@email.com'
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'idurar-crm-erp'
